config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:CVS807YirBrmwzZPg7ZusmuQlRk2Z5fA7q0FL6or748=,iv:dcakolSW8odoMR9rZJQeRoSdfpTfVNMjs9ErldLk4ec=,tag:ycKc15UcW7MtsARklJk+Uw==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:gvtwPHReMmaaKcNWUcf63NO6GpAiiyLRimQkuJC1qKlSa/leVe5oLJzY9/3JkY4S9LJvs7JI2MT2AvUgMRd+qPfMHySgosOQPxx0PJAtp6ikfAKb,iv:t9Pb1+XKP5B2VwA9c9fguR/oULpIETFngt0cmqJPb7I=,tag:ABBYMiyjUW/dsUESQB1Uqg==,type:str]
        AZURE_APIM_API_KEY: ENC[AES256_GCM,data:ceGyPsjjZ09T3U+zAJdTaqYr3ly5/wW4GYtJxd0noTI=,iv:1chC8dCnBhtqCd8Ex34dlSAO3LT+9IlbI5SQXdXt79U=,tag:2qd1zxwpDnKwFcGVZE8siw==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:T+LaC4wkSed2ZbuZZA9EnqsZ,iv:7JM9iNYjLQ63kqZ5AtDODkE0BELWRal3wTB4G8W8Kho=,tag:IRUsvN4EowdEhJsSx++7Mg==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:b0QcVmOiCxTrMqxPi+jI/NFOB4Zo6QA=,iv:IO39BNbdBcsLMYX5BydeQWM5oSIGPz66ldYKkGPmy7Q=,tag:UmkHbz1x90RoZ7Nw2gi02A==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:TTK/V7kI3W7UC4P2OoIJiCW+eM78j7+nhPK007sYwlhLRv6Q6dXIYT3jjPyz2r8HJBBnLM5t4leWU+97jDtYYEwIrdGDmEAw8z98vLchU8d+O8Q5CfXlSg==,iv:eETF+0rF/X9GyIGKQujbRM+KeGZvzeCtqYrE7e4VaPQ=,tag:S99K8hY6JEEoPjWMYXINFw==,type:str]
sops:
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeXRNRVd6cEloY3gxSjBm
            RGFwbmROS3MwWHR4VmttSWNqaEFUUTN3dUc4CjQ1Z0dDUks2bENKY3ZTYnUrNlg2
            ZTVkRitvdVJGbmVjK3k0RVRYYWFOREUKLS0tIEFIN1hPVHFLbE40R3JQU0UyVzQ0
            WnAwOVZ1ZjJXZ2RZMUFnaG5HcVlUc2sKxNziAEyoLJ6axc6LV+oKPtpbzqXNt5xF
            pOgSwl8XniM/9Mz6z2zcLBRggPHpNSMEJXtG7+sDlf1Jw7kpxriyLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVDEzankveG5hTjBibzd1
            OGc3TGI0YW5EMUtlTCt5VWo2cVVqemVTMERNCmFWeEM0VHdpeFI2Qjh6NHFOVFdF
            OXR0NUVROTRTUlFCTmRKRkxQR0xCeE0KLS0tIGtUei9MT1pqM2FUT1UxaWNrS2tT
            dVpNRzFaZFN2c3d0UmFWYThic1JjME0K4gKxXnjMHEGDwBbwu7L1L31LElvC7sdo
            Ldj1KY43XIp/rCoLBSln1FfwbenZbqZVr5iyy8QSEFv2kTXVubNsNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreWpsQXpLYXNYdzVTYUpq
            bWNHTmY5RTZqTzRLOUI4M0ptNGsyM0FjeFFZCkQ2K0NHbE56UXlpTVhxcGdBMnhq
            RzdlU0xmNWovekJnLzZsWlAxTnYweXMKLS0tIHZLaEowTVl4YzdNRkVZOWEyQjha
            SDZGL3FGaU1FWTZkMlRSWldQVFdQRlkKn2jkba56M6bJBDLJid8VS9P3/pzofJIJ
            Vxgmko8KdDXu6ecnQ9N0EDYZPQ+KQyNexeisptZFOcpJO7KlL07d8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeWorUWcvMnBHTEI5V2Rs
            VS8xNnloTklMNTdRUEFpMmtNc0M5SWpjNTJNCkRQZ1RUK0NlOHo4SWcwNHN5YjhB
            Y0l2QUUzclNGVEZFSWZweEoyaVVPMTgKLS0tIFIvU3NTbi9iejcxK1grNHNyN2hq
            ank2eHlyclUwbFZPYmsxZlA4OEFoSWcK4V+LMWlN4feEv6DLJmLAsr1ksfaK4oq2
            0pD4bATmdZExXWLCW9/GBtOFUYbP4ZF5cttqQZACWA0fFE3pgb8OgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQ0Rnd2RHR2lid1ZLQmd0
            dERHQUZ6RnNxZGNUREtFR0NzNlplbzZiQUU4Ckk2VXhma0ZUTzNseUw5YzRuWG1s
            SjdtbncxV1hDMTNydHJMYmhnclowR1UKLS0tIE05bVRlM0g5dFNXRFJMTTFnaWlx
            dy9BOHJEZnFHTHd6V0VuVmRHM0x0UTAKD6fNXT/uW8t5TRJmSRWuptaZFstQY1Cg
            /KX7BucAsHRruZZEQDLRoLYvdbwFf5qwzyRO/uQQxIMQG5F2ZVkPuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSDFJYmo4TXFudFgzY3li
            R1RJMDdYeXBiYzlOMmphM3hLNXVUSzFhc0NJClhmOFhoaHBDMEwxWGRWRlRSOURF
            WXpJbHl5VEhqeStLRW5VeWhSUUFac00KLS0tIE4zNUw1d0djU0RSSGg1L0RiM0tw
            ZjYvVUx5Y2UvblUwemdsYVdDWEN6bXcKd7kv1FAE5d1ROzveRc+1LJHOox3Xy7Ve
            vrDdYftAyCYvY5PSC82+/JiV0lqKwEx5+xLradzLB1lOb8F45px4Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:12:42Z"
    mac: ENC[AES256_GCM,data:sOEfKW8r/ruDBv/6pTJHPyw99TGL+JmFTyV8PbB8ZaeOwoa3zWei+XCvdeS7f35p3neYy/u0qznxI1qhowSxSQt6LtPdwqGezxEb8wkLI1SXwUH5kp4TcU7mDusBduMY5zomH+THviqDo8NlWz86gpElleyYTnnnWntd8oICFFM=,iv:O9+oxLcTVopjq6S+zrNfHN1CrrQ4gUc2Zb9HLCqWAfA=,tag:w5PVJeqB6c7gBu8YgPm0ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
