config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:vU5sozgleY904OU1Fb0yEaRzWYNHnCD2ILjthvtSfk4=,iv:b7ItArThdtIsz1qvgpptbOq96GHa1q6VWAweHYWw2Po=,tag:emJB+azc6vcIWCgv8idtyg==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:FjMSqC6wQM4/1cg5hwM3qAZiKmDEEU0rz6l44XDr0HQ0WLXRYKxDcm/0Ii1khG693fyQJalH7lvf8CRVdD4mnIm3KOaw5Q5MCkqrqoQo2GGm+7ZF,iv:h157m7hUESIOMC81yrnxzG//fInFLfsR8o2zYTsGcUs=,tag:pMOQn7+ijCbvYh1AksjYbQ==,type:str]
        AZURE_APIM_API_KEY: ENC[AES256_GCM,data:GKEHlKS5GgzSO+rHYYvrdL0e7WDZDyByD6mYbDmSNZQ=,iv:k/SHzVKSvMr0ibz3O19yQc3Hz4rzFRALxINlNJRLAwk=,tag:9sgSAnfTKEL5SDPyyw2uhA==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:8GsISVAuJyIh0WUFwb9mpqyWcNT04fnmpH4ru5CA+aw=,iv:oGKLDiadbhRQWVSE5J/4QJbppiTIcHhNr9fFY7XI0jY=,tag:Ksk0uMrB9fmVT8thQODFJA==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:vhsGuyM8IYCRua2BQtuYpLI/Dzdx,iv:kPcuAWarV4RXujfwe+9rKe/YWARoeOcFp789WwrI+z8=,tag:Hg8JJmYW0Zuz/2brM/z8yQ==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:xssnW7Kk3LGmF9dpeCiiV2Z7vyNo4n0aSMcA3aXJYd7uvx7B1HmmSRnc47y3pBS8Hg0dc+6Lf0AIod/Yr2mMC+Dfoosfj2oiY4P/7FQZNMD2xVuZCebTYA==,iv:wlEwj0M1U/EIgVbqxiT0aLgtcwmVGfuRgTaOdQYs6IU=,tag:pLiJujwzEMZOg1xEM22Ojg==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R2xCeHAybzc0Zlk4ME04
            VFZkQ0s1c2FsdE01S28zMHNtSzAzbkhvZmxzCkpEM0VRRzVFdWtJTFVRcHVGSXJR
            aWZzRWxxY1FuMjdKUkdoN0crOG42YzQKLS0tIEUrekxvZjFrWDJNR1Q2YldUWER1
            S1JiK1ZkMld1RUJ0M3VsYmVJL2VWTGcKGw3xqNeYzREDyQunsEHU7ajxcOAoUCcZ
            L6gmMPI6bZfyW8Sq2u4wYt6MrERovBoEFpFm4UmUnfCxodMjZyNjIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNG5GMWE1bjlsekVoS041
            UjdkVWpPRURTdEhPQmJCVzF6MFBQQXZXNGhBCjBEaXFEaC9VcUtYanRHSUhMR0Qw
            dmdYb29WdnU3RkFkNjNwOGV6b3Blc1EKLS0tIFBJeDBjTTVkVWxZQUR2Q2RkMFhV
            aUdEOC9jVFNvMVhxQnBtVmVDcmJubVUKHRnjxPYRBbrzP9LjUsvcyFh87mgvUl1P
            PcrgsOOOvu4lHyiF1m5KUR9h8G88NNIv0VggNYfOV7o4bsy691v12Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTmVaSTdvK29lcVJwL0l4
            ZU52Vko3RVVqd2hhYVVCdWJtU3VTaHZ3U2gwCkdoSmVUNk5IOEw0TXozVXZBSFht
            QmFHK2JPUVpZSlI1Zi85Y0o2OWUrR0EKLS0tIFpTekdGN0U4TEtaYjhPNXlXTUFt
            RU85UENjSGs5K1c0SlRKdUxsM1RkZU0KWtcCdceXPaEORejTjPyVHi0tqiXt6lAJ
            tN453Uqcj6Y3rE3dO6LdrYChl1gY8XIxPyeYjZpe0Gg3AqdvUw1RRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN1YxZWhnS3lGVGlLY1lL
            Q1M3eFpGb1ZJTGdCOGFwbTBKVFBZZUdRNlNnCnJ1ZThYeC9lVFlzSWtQd3EvNkVW
            bmc3N25hVmJJSUZJTk5NN2ZRbjA1dkkKLS0tIEZRQXNlT2ZqVVJUOXhSTEUyei9T
            TzE4ZWpkeWp6STZsVW1YMk90aGh4ZVUKh0c2Uu2WY6wWGqJv/SUElqKSRBURdGB4
            kdIVLW5hskirKX8RMkvqY0aCc+RA+AIwAYSdpIT5+GhGYvf3WwcSAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN1o1Tmtkb0NadFJESXVj
            K3VFNjlLa1pqSjhheW5kbEZWWmcrNHBiUHpZCkRwMUNiUDdxRVAzVk10VzJvYnIy
            VnlqUEVjSnF1eUJHYkVhNEwvMmNpeGcKLS0tIFBpR0hTWHIwMUd0emdxM2k5Q1NB
            NXZiYmdGZURyQ0xyeE50Z1VDa2wyY1kK/5iryku0MKcs4lCPGOVayJVNA1QN8h72
            NIUYWr0VHSfHe7oBzC81kk2I9gg4Pa3cORZyhIzxEU2ytJPBmDinCw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL1BFY1MxQkxTZlBUNlFU
            SkRvWGdZczJyZEJDTlRxZUdZVWVLQXFuRms4CkRCSjhtYmhkSEwzRHZtUjhHOGkv
            OW1hWHNRYWw5VG41c2NNUnJxVW1tWXMKLS0tIGE0NDBZRWphSjhrcGJvaEpEUG5M
            Q1lsakJjbW5rTGRIYUt0M3ArN2xjMW8KyUV4W7zltLlQ3Bdp4U1OgU5hRlWLa5RU
            hxOYlyFSCKkn/hXTx2AAwyTVcwVGt/OoUujuRN1A1/pGrO1sDY0uFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:12:47Z"
    mac: ENC[AES256_GCM,data:FL4ZyGT2BoO/xUYY4ZEvQqf1nTuLMbX8wE0tvghsFlnOp7bhINuZBA9Mc5xK5dsy5LkVesVV60CtMXu6yhNJUxGRcyrZHkrQnvUX+0qVh4GqRPxhFRP++e8oOFbsVs+XTwZSpJNN740VV27B5NbsM6lXbWi4DGH1q+aL2qE2EuY=,iv:lVWWYPAwkfNg9dJJtTRvD3mYmLcOnvId6fDsndNE6qc=,tag:T4sAj8BPtVzjABw++ejy7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
