config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:vU5sozgleY904OU1Fb0yEaRzWYNHnCD2ILjthvtSfk4=,iv:b7ItArThdtIsz1qvgpptbOq96GHa1q6VWAweHYWw2Po=,tag:emJB+azc6vcIWCgv8idtyg==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:FjMSqC6wQM4/1cg5hwM3qAZiKmDEEU0rz6l44XDr0HQ0WLXRYKxDcm/0Ii1khG693fyQJalH7lvf8CRVdD4mnIm3KOaw5Q5MCkqrqoQo2GGm+7ZF,iv:h157m7hUESIOMC81yrnxzG//fInFLfsR8o2zYTsGcUs=,tag:pMOQn7+ijCbvYh1AksjYbQ==,type:str]
        AZURE_APIM_API_KEY: ENC[AES256_GCM,data:GKEHlKS5GgzSO+rHYYvrdL0e7WDZDyByD6mYbDmSNZQ=,iv:k/SHzVKSvMr0ibz3O19yQc3Hz4rzFRALxINlNJRLAwk=,tag:9sgSAnfTKEL5SDPyyw2uhA==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:8GsISVAuJyIh0WUFwb9mpqyWcNT04fnmpH4ru5CA+aw=,iv:oGKLDiadbhRQWVSE5J/4QJbppiTIcHhNr9fFY7XI0jY=,tag:Ksk0uMrB9fmVT8thQODFJA==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:vhsGuyM8IYCRua2BQtuYpLI/Dzdx,iv:kPcuAWarV4RXujfwe+9rKe/YWARoeOcFp789WwrI+z8=,tag:Hg8JJmYW0Zuz/2brM/z8yQ==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:xssnW7Kk3LGmF9dpeCiiV2Z7vyNo4n0aSMcA3aXJYd7uvx7B1HmmSRnc47y3pBS8Hg0dc+6Lf0AIod/Yr2mMC+Dfoosfj2oiY4P/7FQZNMD2xVuZCebTYA==,iv:wlEwj0M1U/EIgVbqxiT0aLgtcwmVGfuRgTaOdQYs6IU=,tag:pLiJujwzEMZOg1xEM22Ojg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUXR1eWxaa29UNnhpQW1S
            VVhVVG9zaEQweStNRk9OTktOajNmNkllQ3lJCkFKckVzOTdyWHlwUXJBcFMxcDhF
            cmdYUHRZcGZPamFBd3dUcDV2eEZBWUkKLS0tIGlRQUpkMTY3bnJ1MzF1dnFyRmpj
            c1AwclcwOW0rQ2c0TVNDMzR4cERBTnMK8awTC1iHGIuMpEkXvO8JufMTpZq1rogv
            HXJVu0QexWVN4gYbaWhmMSo6UUEawEKhnXh8AQieE/s8HTk8NOALTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWlJsSTR5ZjNLMmhNazhu
            WG8zT3UrRHNHUUNHQ01oSUUzWXpORkJpZkE0Cml1di9USkt5WUF2UlBZSFpxWTZl
            aE5mQk9mWm91dGdUS1dnNmYxSmUxSVkKLS0tIFI1cWp0bEN2cVNrY25NRE4xdjBY
            ZW96TnVaL21sdGJDcVo4dnUzalM5MlkKs+o15Xm7uiPTt0dUxuvILbvWtTr8Dmfh
            rzpkkWF1/temHcCzM1vAmBFQ2z3+Ub+5r1wVkPMCZ7rbkMJ3QtD8Dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeEs5aHI2QVIxRVJ1WVlS
            MkhsNEhrOXR5c3dVRW5Tb1VPUlVPY2o1b0dNClM3Vms1Q2J1LzN4K0Nrc1VRK3ZR
            dkZxTTNSdHJLTC9tWTZhQThmUVh2NFUKLS0tIGZ2YndIU3d4Mk15WkVGRDZhM1U4
            RzlMakhrQVFNZGF4UC9IdmN3VlFDNXcKoIARTtY3sLiJJNhCYPvkleupVKLIEzPY
            dLEQhgKKWeYwyumIdDMhSgmlRxzbUh1JFOU6MC50IFAEjarKBb7pCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMzRxMXdDbzd3bER1Q3da
            eXZYOENqa2tZbHlYQjh1aTgwQkpmR3dlL1N3CkFqOHptbHpkUDQ3VTVSbDRaOWh5
            SVhyb0U5UFVRSTYxakpCNy9xYlVkdVkKLS0tIG9wZnJtQ3MwU1d5U2F2UDBrbXFX
            UFdBaUQ0MFBOdThxRk1vVkZ1K2xhZGMKMYDETh3trPcmABkzECVuK1Fhp0DlZzW/
            mkDaEw22Ey3koXUA+XJxFMhVyzkeT6V7jPe5nHySVmkCXvkhM1VQUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:12:47Z"
    mac: ENC[AES256_GCM,data:FL4ZyGT2BoO/xUYY4ZEvQqf1nTuLMbX8wE0tvghsFlnOp7bhINuZBA9Mc5xK5dsy5LkVesVV60CtMXu6yhNJUxGRcyrZHkrQnvUX+0qVh4GqRPxhFRP++e8oOFbsVs+XTwZSpJNN740VV27B5NbsM6lXbWi4DGH1q+aL2qE2EuY=,iv:lVWWYPAwkfNg9dJJtTRvD3mYmLcOnvId6fDsndNE6qc=,tag:T4sAj8BPtVzjABw++ejy7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
