config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:vU5sozgleY904OU1Fb0yEaRzWYNHnCD2ILjthvtSfk4=,iv:b7ItArThdtIsz1qvgpptbOq96GHa1q6VWAweHYWw2Po=,tag:emJB+azc6vcIWCgv8idtyg==,type:str]
        AZURE_GPT_4O_API_KEY: ENC[AES256_GCM,data:Kggxdo8yaKEz8jbv2oc4vVLGiIaiu2cr0EMRG/3QOas=,iv:pOkCiKhlECCBS1q5Lfb5xIycJ79se43nLgWgseEe23o=,tag:FHY6YbrTaUh0pQodu/dvVw==,type:str]
        MISTRAL_API_KEY: ENC[AES256_GCM,data:7Oqb2b3PZEbuqhSBGjqRQYz637xnho4D1T4Bkg+oBk0=,iv:6/RMp5QRcz9Rvku6l+j9w7qVtBp7to4fc5wQ+iWMjxA=,tag:dCGleGpG+6EPj1OJF6KTWQ==,type:str]
        AZURE_MISTRAL_API_BASE: ENC[AES256_GCM,data:6T5IvRtmlfyTmhUY7pGeMcOOPU+9P27TAVVfqlyAjGBLJ8I0ypJ5DwVsP3KjejL00L1mIg==,iv:3TI3Isk+B8IyUyiafn6TTgj24H943NcHPZYI7KfaQmA=,tag:08KnK3qUqTT1DzmeIfSAGw==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:FjMSqC6wQM4/1cg5hwM3qAZiKmDEEU0rz6l44XDr0HQ0WLXRYKxDcm/0Ii1khG693fyQJalH7lvf8CRVdD4mnIm3KOaw5Q5MCkqrqoQo2GGm+7ZF,iv:h157m7hUESIOMC81yrnxzG//fInFLfsR8o2zYTsGcUs=,tag:pMOQn7+ijCbvYh1AksjYbQ==,type:str]
        AZURE_MISTRAL_API_VERSION: ENC[AES256_GCM,data:4gJ1zw0zQrkkJEo+klM6Td4S,iv:CQo3BlrNxWVCdObufXZhxp6/QoCYJCZidUO67B+my6A=,tag:7BKaVi5d5Q+VFM+ofAvK7Q==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:8GsISVAuJyIh0WUFwb9mpqyWcNT04fnmpH4ru5CA+aw=,iv:oGKLDiadbhRQWVSE5J/4QJbppiTIcHhNr9fFY7XI0jY=,tag:Ksk0uMrB9fmVT8thQODFJA==,type:str]
        AZURE_LLAMA_31_8B_API_KEY: ENC[AES256_GCM,data:1QoINoywOPJnzFrdHMaTua1QFF0zDfhOsRSq5BZMFbc=,iv:SdvSiIUsv2kG7pA7T7Bcr/WYcXIhX9RPrFAgpzhtb10=,tag:AvmJFATaTbYiSi5j542eEQ==,type:str]
        AZURE_LLAMA_31_405B_API_KEY: ENC[AES256_GCM,data:ZxE43p+30+vAORaSlMwR+RcfQ2lJRe/7s/mTqs65J/I=,iv:XUM2Zkt/UQ2wZZkagsbpT4cknzA/1BWl5/DGV3FjKuM=,tag:IDVEPE2RDFznWsFM62jc1Q==,type:str]
        AZURE_LLAMA_31_70B_API_KEY: ENC[AES256_GCM,data:birV24bvEeW+4IDW6T7bkGVxo1u0G3qf8zBtlUb5Q68=,iv:drqUMWQOMc5f3AUlK4gDIg+cVYzj/gDcVW5knbAzLEE=,tag:h9ahy7/SL73yGxRduQFwUg==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:vhsGuyM8IYCRua2BQtuYpLI/Dzdx,iv:kPcuAWarV4RXujfwe+9rKe/YWARoeOcFp789WwrI+z8=,tag:Hg8JJmYW0Zuz/2brM/z8yQ==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:xssnW7Kk3LGmF9dpeCiiV2Z7vyNo4n0aSMcA3aXJYd7uvx7B1HmmSRnc47y3pBS8Hg0dc+6Lf0AIod/Yr2mMC+Dfoosfj2oiY4P/7FQZNMD2xVuZCebTYA==,iv:wlEwj0M1U/EIgVbqxiT0aLgtcwmVGfuRgTaOdQYs6IU=,tag:pLiJujwzEMZOg1xEM22Ojg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUXR1eWxaa29UNnhpQW1S
            VVhVVG9zaEQweStNRk9OTktOajNmNkllQ3lJCkFKckVzOTdyWHlwUXJBcFMxcDhF
            cmdYUHRZcGZPamFBd3dUcDV2eEZBWUkKLS0tIGlRQUpkMTY3bnJ1MzF1dnFyRmpj
            c1AwclcwOW0rQ2c0TVNDMzR4cERBTnMK8awTC1iHGIuMpEkXvO8JufMTpZq1rogv
            HXJVu0QexWVN4gYbaWhmMSo6UUEawEKhnXh8AQieE/s8HTk8NOALTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWlJsSTR5ZjNLMmhNazhu
            WG8zT3UrRHNHUUNHQ01oSUUzWXpORkJpZkE0Cml1di9USkt5WUF2UlBZSFpxWTZl
            aE5mQk9mWm91dGdUS1dnNmYxSmUxSVkKLS0tIFI1cWp0bEN2cVNrY25NRE4xdjBY
            ZW96TnVaL21sdGJDcVo4dnUzalM5MlkKs+o15Xm7uiPTt0dUxuvILbvWtTr8Dmfh
            rzpkkWF1/temHcCzM1vAmBFQ2z3+Ub+5r1wVkPMCZ7rbkMJ3QtD8Dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeEs5aHI2QVIxRVJ1WVlS
            MkhsNEhrOXR5c3dVRW5Tb1VPUlVPY2o1b0dNClM3Vms1Q2J1LzN4K0Nrc1VRK3ZR
            dkZxTTNSdHJLTC9tWTZhQThmUVh2NFUKLS0tIGZ2YndIU3d4Mk15WkVGRDZhM1U4
            RzlMakhrQVFNZGF4UC9IdmN3VlFDNXcKoIARTtY3sLiJJNhCYPvkleupVKLIEzPY
            dLEQhgKKWeYwyumIdDMhSgmlRxzbUh1JFOU6MC50IFAEjarKBb7pCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMzRxMXdDbzd3bER1Q3da
            eXZYOENqa2tZbHlYQjh1aTgwQkpmR3dlL1N3CkFqOHptbHpkUDQ3VTVSbDRaOWh5
            SVhyb0U5UFVRSTYxakpCNy9xYlVkdVkKLS0tIG9wZnJtQ3MwU1d5U2F2UDBrbXFX
            UFdBaUQ0MFBOdThxRk1vVkZ1K2xhZGMKMYDETh3trPcmABkzECVuK1Fhp0DlZzW/
            mkDaEw22Ey3koXUA+XJxFMhVyzkeT6V7jPe5nHySVmkCXvkhM1VQUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T16:55:05Z"
    mac: ENC[AES256_GCM,data:jvwXDTD+zufd7gNPVRz8tVRikv7Pz6cgxjmy7+Z0Q90BfGSiKwqME+nayOxEP3i6qMAWYDvCVNLio56GIXR3ppTZultqrlzJIK3Okw5jeLxcEsnYOTY/O6YfWv6bJ5SQ1ZNboNE/4QLmIsnql73hvJvWy24ptWFWoAvo6Sgzs54=,iv:KivpLNSqW4Mk5TFjgg1VkxAFygMwa16cNAbCD6HL09w=,tag:Wjd/hI/PPXgHTeDQBUtH7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
