config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:CVS807YirBrmwzZPg7ZusmuQlRk2Z5fA7q0FL6or748=,iv:dcakolSW8odoMR9rZJQeRoSdfpTfVNMjs9ErldLk4ec=,tag:ycKc15UcW7MtsARklJk+Uw==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:gvtwPHReMmaaKcNWUcf63NO6GpAiiyLRimQkuJC1qKlSa/leVe5oLJzY9/3JkY4S9LJvs7JI2MT2AvUgMRd+qPfMHySgosOQPxx0PJAtp6ikfAKb,iv:t9Pb1+XKP5B2VwA9c9fguR/oULpIETFngt0cmqJPb7I=,tag:ABBYMiyjUW/dsUESQB1Uqg==,type:str]
        AZURE_APIM_API_KEY: ENC[AES256_GCM,data:ceGyPsjjZ09T3U+zAJdTaqYr3ly5/wW4GYtJxd0noTI=,iv:1chC8dCnBhtqCd8Ex34dlSAO3LT+9IlbI5SQXdXt79U=,tag:2qd1zxwpDnKwFcGVZE8siw==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:T+LaC4wkSed2ZbuZZA9EnqsZ,iv:7JM9iNYjLQ63kqZ5AtDODkE0BELWRal3wTB4G8W8Kho=,tag:IRUsvN4EowdEhJsSx++7Mg==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:b0QcVmOiCxTrMqxPi+jI/NFOB4Zo6QA=,iv:IO39BNbdBcsLMYX5BydeQWM5oSIGPz66ldYKkGPmy7Q=,tag:UmkHbz1x90RoZ7Nw2gi02A==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:TTK/V7kI3W7UC4P2OoIJiCW+eM78j7+nhPK007sYwlhLRv6Q6dXIYT3jjPyz2r8HJBBnLM5t4leWU+97jDtYYEwIrdGDmEAw8z98vLchU8d+O8Q5CfXlSg==,iv:eETF+0rF/X9GyIGKQujbRM+KeGZvzeCtqYrE7e4VaPQ=,tag:S99K8hY6JEEoPjWMYXINFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeHpZWlNUdDZkMDNmNmtJ
            eU9nQU01Q0I0YS9oYmtVaGNRa0V3SGFwQzMwCkYzajZLdkNCcXRPY2lsRGNjRExt
            a1VRQ1lTMUZtUkZ2ZitSZHAxZ0k0NWcKLS0tIDhjdDZDUnEwYVdxcTRqdk1xUHBu
            Z1VEOUhrTlp1K3Y4Rlg3STRmOVdKUkkKfqIKmgqk+64/oRmuvO//loTEAjxYwZFr
            +y4Fpd0g7sRqz1EZDDiAiRHTWGYqWslP+/lptTCAzr+JPhvIU+4BPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNmdYYkJtaFJJYmJxMkJa
            SWZlNXo5WHAyS3BpSkRJVTdvVWZ5em1UOERrCml5OXo5NHJDVm9sWXJPT2RtN1hL
            Y3JlaVVxNDMycjk4K2V0RzZST2w5K2sKLS0tIDdlYkQ4NnEveXF0RkRHWmtPcDJ4
            V3RZSDNseWYrVGZ3N0hiVWVCL214a1EK1u5loXbv0+QojP9hTLFdBbQNo+BIckDC
            M4RVJhKoyMJuzR7cZSqHETFJVlkzcKrPP6/EloOMEsiKSAkrjYgTBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbm9iTFBkTmhwNFI5aEZs
            QWJFTllYK2lIZTFaU1Nxb2FDWDZGR3VTaVVZCkhXUHFTZmw2Mmp0TEIxRWwrZ3Nn
            OFVESTUxV0JweVJ6eDF1RVVvQkdNSmMKLS0tIGE0b3RwbWhoOG9MYXFJSFVwcHc1
            WlI5bnZGL01ZN0JvRzNKY2dhcUdPYzgKysQFkekpN0rCWJFZXQ0sBwApnADc1Tef
            ur1UkarYysOQd/O2c1RrIOnWRiKzZ4JUO16dYnEHTOEUn+sTQWBn4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcDZkM3JtYkhocXdMV2Er
            MmRieTlZM0d0eC96eDlWRjA1TUxyVzlxam1zClJYNFlsZWZobWp0eWYvVkR1K1lv
            K3o3Y0RINHRjelk3bkJYTDVrWmZiS2cKLS0tIHB2aW0xazdMVDZ3OGRQSHM4a0dm
            QUdraDE4NTJRYU9ub2lxNVN2SWNLYjgKW+tADcGDMoHVFV66uy+swFv0gP5vN3Fn
            lw46LJiG2QMWV12AluWIFADKDoSQxr/GZtBtziHzlhv6GikGEnCaMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T11:12:42Z"
    mac: ENC[AES256_GCM,data:sOEfKW8r/ruDBv/6pTJHPyw99TGL+JmFTyV8PbB8ZaeOwoa3zWei+XCvdeS7f35p3neYy/u0qznxI1qhowSxSQt6LtPdwqGezxEb8wkLI1SXwUH5kp4TcU7mDusBduMY5zomH+THviqDo8NlWz86gpElleyYTnnnWntd8oICFFM=,iv:O9+oxLcTVopjq6S+zrNfHN1CrrQ4gUc2Zb9HLCqWAfA=,tag:w5PVJeqB6c7gBu8YgPm0ww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
