ingress:
  hostname: api.welearn.k8s.lp-i.org

config:
  nonSensitive:
    PG_HOST: prod-prod-projects-backend.postgres.database.azure.com
    TIKA_URL_BASE: https://tika.k8s.lp-i.org/
    DATA_COLLECTION_HOST_PREFIX: workshop
allowedHostsRegexes:
  alphaUrls: |-
    https://[a-zA-Z0-9-]*\.alpha-welearn\.lp-i\.org
  mainUrl: |-
    https:\/\/welearn-demo\.learningplanetinstitute\.org

rateLimiting:
  enabled: true
