ingress:
  hostname: api.welearn.k8s.lp-i.dev

config:
  nonSensitive:
    PG_HOST: dev-lab-projects-backend.postgres.database.azure.com
    TIKA_URL_BASE: https://tika.k8s.lp-i.dev/
allowedHostsRegexes:
  mainUrl: |-
    https:\/\/welearn\.k8s\.lp-i\.dev

rateLimiting:
  enabled: true
