{{- if .Values.rateLimiting.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.rateLimiting.middlewareName }}
spec:
  rateLimit:
    average: {{ .Values.rateLimiting.average }}
    period: {{ .Values.rateLimiting.period }}
    burst: {{ .Values.rateLimiting.burst }}
{{- end }}
