{{- with .Values.rateLimiting }}
{{- if .enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ tpl .middlewareName $ }}
spec:
  rateLimit:
    average: {{ .average }}
    period: {{ .period }}
    burst: {{ .burst }}
{{- end }}
{{- end }}
